### ISSUE TITLE
Error with saving the visualizer video

### ISSUE THREAD

**Issue by satyajitghana** [Xharlie/pointnerf#76]
```
--------------------------------Finish Evaluation--------------------------------
Traceback (most recent call last):
  File "/mnt/thor_hdd_01/satyajit/experiments/pointnerf/run/test_ft.py", line 353, in <module>
    main()
  File "/mnt/thor_hdd_01/satyajit/experiments/pointnerf/run/test_ft.py", line 350, in main
    test(model, test_dataset, Visualizer(test_opt), test_opt, test_bg_info, test_steps=resume_iter)
  File "/mnt/thor_hdd_01/satyajit/experiments/pointnerf/run/test_ft.py", line 264, in test
    visualizer.gen_video("coarse_raycolor", range(0, total_num, opt.test_num_step), test_steps)
  File "/mnt/thor_hdd_01/satyajit/experiments/pointnerf/run/../utils/visualizer.py", line 92, in gen_video
    filename = 'video_{:04d}_{}.mov'.format(total_step, name)
ValueError: Unknown format code 'd' for object of type 'str'
end loading
end loading
```

**Comment by satyajitghana** [comment]
well i just removed the :04d and it worked

**Comment by LeoRainly** [comment]
Why can't the generated video "xxx.mov" display?

**Comment by iszhihao** [comment]
> 为什么生成的视频“xxx.mov”无法显示？

I have the same problem,do you sove it?
