### ISSUE TITLE
Issues with custom Training Data

### ISSUE THREAD

**Issue by satyajitghana** [Xharlie/pointnerf#78]
Hi,

I'm trying to train PointNerf on my Custom Data, which is very similar to Nerf Synthetic COLMAP data, but I'm having trouble loading my point cloud

```
torch.Size([2989992]) torch.Size([2989992]) torch.Size([2989992])
load points_xyz torch.Size([0, 3])
Traceback (most recent call last):
  File "/mnt/thor_hdd_01/satyajit/experiments/pointnerf/run/train_ft.py", line 1081, in <module>
    main()
  File "/mnt/thor_hdd_01/satyajit/experiments/pointnerf/run/train_ft.py", line 690, in main
    _, sparse_grid_idx, sampled_pnt_idx = mvs_utils.construct_vox_points_closest(points_xyz.cuda() if len(points_xyz) < 80000000 else points_xyz[::(len(points_xyz) // 80000000 + 1), ...].cuda(), vox_res)
  File "/mnt/thor_hdd_01/satyajit/experiments/pointnerf/run/../models/mvs/mvs_utils.py", line 541, in construct_vox_points_closest
    xyz_min, xyz_max = torch.min(xyz, dim=-2)[0], torch.max(xyz, dim=-2)[0]
IndexError: min(): Expected reduction dim 0 to have non-zero size.
end loading
```

although the fused.ply seems fine

```
   ply
   format binary_little_endian 1.0
   element vertex 488944
   property float x
   property float y
   property float z
   property float nx
   property float ny
   property float nz
   property uchar red
   property uchar green
   property uchar blue
   end_header
   ]V?H,^D?@VR??g?>{K?>
```

I'm not sure what could be going wrong

**Comment by kaichen-z** [comment]
I think that this problem mainly comes from the previous filtering process consisting of several steps, you probably need to check each step for number decreasing.

**Comment by iszhihao** [comment]
> 嗨，我在运行自己的数据集时遇到了同样的问题，就像“加载points_xyz火炬。Size（[0， 3]）“，请问您已经找到了这个问题的解决方案？

请问您已经找到了这个问题的解决方案？我在更换了MVSNet的模型后，也遇到了这个问题

**Comment by jmchensc** [comment]
你好，后续工作没有在pointnerf基础上进行展开了





------------------ Original ------------------
From: iszhihao ***@***.***&gt;
Date: Thu,May 16,2024 11:23 AM
To: Xharlie/pointnerf ***@***.***&gt;
Cc: jmchensc ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [Xharlie/pointnerf] Issues with custom Training Data (Issue #78)





  
嗨，我在运行自己的数据集时遇到了同样的问题，就像“加载points_xyz火炬。Size（[0， 3]）“，请问您已经找到了这个问题的解决方案？
  
请问您已经找到了这个问题的解决方案？我在更换了MVSNet的模型后，也遇到了这个问题

**Comment by 1FUSANGSSHU1** [comment]
> > 嗨，我在运行自己的数据集时遇到了同样的问题，就像“加载points_xyz火炬。Size（[0， 3]）“，请问您已经找到了这个问题的解决方案？
> 
> 请问您已经找到了这个问题的解决方案？我在更换了MVSNet的模型后，也遇到了这个问题

您好，可以问一下个人pointnerf数据集是怎么制作的吗
